import SEO from "@/components/SEO";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-7">
    <h2 className="font-display text-xl font-bold text-foreground mb-2">{title}</h2>
    <div className="text-muted-foreground text-sm leading-relaxed space-y-2">{children}</div>
  </div>
);

const Disclaimer = () => (
  <>
    <SEO
      title="Disclaimer | FreeATS"
      description="Read the FreeATS Disclaimer. Our ATS scoring tool provides general guidance and does not guarantee job placement or ATS compatibility with any specific employer system."
      canonical="/disclaimer"
    />

    <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12 w-full">
      <h1 className="font-display text-4xl font-extrabold text-foreground mb-2">Disclaimer</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: March 20, 2026</p>

      <Section title="General Disclaimer">
        <p>The information provided by FreeATS (freeats.vercel.app) is for general informational and educational purposes only. All information on the site is provided in good faith; however, we make no representation or warranty of any kind regarding the accuracy, adequacy, validity, reliability, or completeness of any information on the site.</p>
      </Section>

      <Section title="ATS Scoring Disclaimer">
        <p>The ATS scores generated by FreeATS are based on general best practices and common ATS criteria. They are not affiliated with, endorsed by, or representative of any specific employer's ATS system (such as Workday, Greenhouse, Lever, Taleo, or others).</p>
        <p>A high score on FreeATS does not guarantee that your resume will pass any specific employer's ATS system, nor does it guarantee an interview or job offer. Different ATS platforms use different algorithms and criteria.</p>
      </Section>

      <Section title="No Professional Advice">
        <p>The content on FreeATS does not constitute professional career counseling, legal, or HR advice. For professional career guidance, please consult a qualified career counselor or HR professional.</p>
      </Section>

      <Section title="External Links Disclaimer">
        <p>FreeATS may contain links to external websites. These links are provided for convenience only. We have no control over the content of those sites and accept no responsibility for them or for any loss or damage that may arise from your use of them.</p>
      </Section>

      <Section title="Affiliate Disclaimer">
        <p>FreeATS may participate in affiliate marketing programs. This means we may earn a commission if you click on certain links and make a purchase. This does not affect our editorial independence or the price you pay.</p>
      </Section>

      <Section title="Advertising Disclaimer">
        <p>FreeATS displays advertisements through Google AdSense. The presence of an advertisement does not constitute an endorsement of the advertised product or service by FreeATS.</p>
      </Section>

      <Section title="Contact">
        <p>If you have questions about this Disclaimer, please contact us at support@freeats.vercel.app.</p>
      </Section>
    </main>
  </>
);

export default Disclaimer;
